global:
  scrape_interval:     15s

# Rules and alerts are read from the specified file(s)
rule_files:
  - /etc/prometheus/alert.rules

# alert
alerting:
  alertmanagers:
    - scheme: http
      static_configs:
        - targets:
            - "alertmanager:9093"


scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 1m
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'nginx exporter'
    scrape_interval: 5s
    static_configs:
      - targets: ['nginx_exporter:9113']
